# Generated by Django 5.0.14 on 2026-09-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Quantity at/below which the product should be restocked.')),
                ('warehouse_location', models.CharField(blank=True, max_length=150)),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'db_table': 'inventory',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('RESTOCK', 'Restock'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGE', 'Damage')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for stock added, negative for stock removed.')),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_date'],
            },
        ),
    ]
