# Generated by Django 5.0.14 on 2026-09-18 03:22
"""
Adds items_subtotal and platform_fee to Transaction, and widens the meaning
of total_amount from "items only" to "items + platform fee" — the amount
actually charged to the customer. See the Transaction model docstring in
apps.transactions.models for the business reasoning. 0004_backfill_items_subtotal
fills in items_subtotal/platform_fee for rows that existed before this change.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='items_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of line-item subtotals, before the platform fee.', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform service fee charged to the customer on top of items_subtotal (see apps.core.constants.PLATFORM_CUSTOMER_FEE_RATE).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount actually charged to the customer: items_subtotal + platform_fee.', max_digits=12),
        ),
    ]
