# Generated by Django 5.0.14 on 2026-09-18 03:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0004_alter_payment_method'),
        ('transactions', '0004_backfill_items_subtotal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('vendor_gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor_commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=5)),
                ('vendor_commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor_payable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=5)),
                ('customer_fee_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_revenue_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_commissions', to='payments.payment')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_commissions', to='transactions.transaction')),
                ('vendor', models.ForeignKey(limit_choices_to={'role': 'VENDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor_commissions',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['vendor', 'created_date'], name='vendor_comm_vendor__b95264_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vendorcommission',
            constraint=models.UniqueConstraint(fields=('payment', 'vendor'), name='unique_commission_per_payment_vendor'),
        ),
    ]
