# Generated by Django 5.0.14 on 2026-09-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_bank_transaction_id_payment_currency_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE payments SET method = 'ONLINE' WHERE method = 'SSLCOMMERZ';",
            reverse_sql="UPDATE payments SET method = 'SSLCOMMERZ' WHERE method = 'ONLINE';",
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ONLINE', 'Online payment'), ('COD', 'Cash on Delivery')], default='ONLINE', max_length=20),
        ),
    ]
