# Generated by Django 5.0.14 on 2026-09-03 05:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('sku', models.CharField(help_text='Stock keeping unit.', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=100)),
                ('issues', models.CharField(choices=[('NONE', 'No Issues'), ('DAMAGED', 'Damaged'), ('RECALLED', 'Recalled'), ('QUALITY_HOLD', 'Quality Hold')], default='NONE', max_length=20)),
                ('expire_date', models.DateField(blank=True, help_text='Leave blank for non-perishable goods.', null=True)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum retail price.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is listed for sale.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='category.category')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_date'],
            },
        ),
    ]
